project_id = "xobhamjwrumrkpxxxozz"

[functions.sync-notion]
verify_jwt = true

[functions.generate-cast-content]
verify_jwt = true

[functions.customer-chat]
verify_jwt = false

[functions.generate-sms-message]
verify_jwt = true
