-- Daily, personalized fitness advice delivered through the existing LINE bot.
-- Training data remains owner-scoped through RLS; only the Edge Function service
-- role can write delivery records or validate the cron secret.

create table if not exists public.kintore_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  goals text[] not null default array[
    '国づくり',
    '居心地のいいコミュニティ作り',
    '健康の最適化'
  ]::text[],
  weaknesses text not null default '',
  notification_enabled boolean not null default true,
  notification_time time without time zone not null default '08:00:00',
  timezone text not null default 'Asia/Tokyo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint kintore_profiles_goals_count_check
    check (cardinality(goals) between 1 and 10),
  constraint kintore_profiles_weaknesses_length_check
    check (char_length(weaknesses) <= 2000),
  constraint kintore_profiles_timezone_check
    check (timezone = 'Asia/Tokyo')
);

create table if not exists public.kintore_snapshots (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  state_version integer not null default 1,
  synced_at timestamptz not null default now(),
  constraint kintore_snapshots_state_object_check
    check (jsonb_typeof(state) = 'object'),
  constraint kintore_snapshots_state_version_check
    check (state_version > 0)
);

create table if not exists public.kintore_advice_deliveries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  advice_date date,
  is_test boolean not null default false,
  status text not null default 'generating',
  content text,
  generation_source text,
  error_message text,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  constraint kintore_advice_deliveries_status_check
    check (status in ('generating', 'sent', 'failed')),
  constraint kintore_advice_deliveries_date_check
    check ((is_test and advice_date is null) or (not is_test and advice_date is not null)),
  constraint kintore_advice_deliveries_daily_unique
    unique (user_id, advice_date)
);

create index if not exists kintore_advice_deliveries_user_created_idx
  on public.kintore_advice_deliveries (user_id, created_at desc);

alter table public.kintore_profiles enable row level security;
alter table public.kintore_snapshots enable row level security;
alter table public.kintore_advice_deliveries enable row level security;

create policy "kintore_profiles_owner_all"
  on public.kintore_profiles
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "kintore_snapshots_owner_all"
  on public.kintore_snapshots
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "kintore_advice_deliveries_owner_select"
  on public.kintore_advice_deliveries
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

revoke all on public.kintore_profiles from anon;
revoke all on public.kintore_snapshots from anon;
revoke all on public.kintore_advice_deliveries from anon;

grant select, insert, update, delete on public.kintore_profiles to authenticated;
grant select, insert, update, delete on public.kintore_snapshots to authenticated;
grant select on public.kintore_advice_deliveries to authenticated;

revoke all on sequence public.kintore_advice_deliveries_id_seq from anon, authenticated;

-- The Edge Function calls this with the service role. The secret itself is never
-- exposed through the API and is only decrypted inside this SECURITY DEFINER call.
create or replace function public.verify_kintore_cron_secret(candidate text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select candidate is not null
    and exists (
      select 1
      from vault.decrypted_secrets
      where name = 'kintore_cron_secret'
        and decrypted_secret = candidate
    );
$$;

revoke all on function public.verify_kintore_cron_secret(text) from public, anon, authenticated;
grant execute on function public.verify_kintore_cron_secret(text) to service_role;

do $$
begin
  if not exists (
    select 1 from vault.secrets where name = 'kintore_cron_secret'
  ) then
    perform vault.create_secret(
      encode(extensions.gen_random_bytes(32), 'hex'),
      'kintore_cron_secret',
      'Authenticates the scheduled daily-kintore-advice invocation'
    );
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1 from vault.secrets where name = 'kintore_publishable_key'
  ) then
    perform vault.create_secret(
      'sb_publishable_T0a9mtOIbupU5n_VAe9caw_xlnbbWfB',
      'kintore_publishable_key',
      'Publishable key for the scheduled daily-kintore-advice invocation'
    );
  end if;
end;
$$;

do $$
begin
  if exists (select 1 from cron.job where jobname = 'kintore-daily-advice') then
    perform cron.unschedule('kintore-daily-advice');
  end if;

  perform cron.schedule(
    'kintore-daily-advice',
    '*/10 * * * *',
    $job$
      select net.http_post(
        url := 'https://imrxzkivwrkqbhqfbbes.supabase.co/functions/v1/daily-kintore-advice',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'Authorization', 'Bearer ' || (
            select decrypted_secret
            from vault.decrypted_secrets
            where name = 'kintore_publishable_key'
          ),
          'x-kintore-cron-secret', (
            select decrypted_secret
            from vault.decrypted_secrets
            where name = 'kintore_cron_secret'
          )
        ),
        body := '{"action":"run-due"}'::jsonb
      ) as request_id;
    $job$
  );
end;
$$;
